extend public API with optional event functions to support additional use-case
mojs/mojs-player pull request #13
Opened 2017-02-14 00:18 UTC by weisjohn

Hey @legomushroom, thanks for making this.

I added these four optional functions so that I could synchronize an animation over-top a `<video>` element. That is, when I integrate with these elements, I can pause, seek, and play the video, scrub back and forth, etc. I can DM a gif/vid of the use case if you want to see a justification of the usefulness of these additions. 

Thanks for considering.

2017-02-14 00:21 UTC, legomushroom commented
Hey @weisjohn ! Thanks a lot, sounds nice, will look into it just shortly. 👍

2017-02-15 03:29 UTC, legomushroom requested changes
Just one nit, otherwise good.

2017-02-15 03:29 UTC, legomushroom commented on js/mojs-player.babel.js
> +    if (onSeekStart) {
Let's be sure an actual `function type` was passed as callback here, we can have `_isFunction` helper and use it for all 4 examples like this:

```javascript
  const { onSeekStart } = this._props;
  if (this._isFunction(onSeekStart)) {
    // run
  }
```

The `_isFunction` can be as simple as:
```javascript
  // ...
  _isFunction (testVariable) {
    return typeof testVariable === 'function';
  }
  // ...
```

2017-02-15 23:42 UTC, weisjohn commented
@legomushroom I just made those changes. I haven't used the "Changes requested" experience on GH yet: do I need to submit a new PR or were those additions enough?

2017-02-15 23:51 UTC, legomushroom commented
@weisjohn thanks! No need for separate `PR` -  I see your commits here. Will review just in few moments.

2017-02-16 04:10 UTC, merged

2017-02-16 04:10 UTC, legomushroom commented
Looks good, thanks a lot. 👍

2017-02-16 04:15 UTC, legomushroom commented
If you want to contribute more, you can think how to provide the callbacks with state variables, something like this:

```javascript
const vid = document.querySelector('#vid');

// connect to player
const player = new MojsPlayer({
  add: timeline,
  isPlaying: true,
  isRepeat: true,
  isSaveState: false,
  progress: 0,
  onPlayStateChange: isPlaying => {
    isPlaying ? vid.play() : vid.pause();
  },
  onSeekStart: (isPlaying) => {
    vid.pause();
  },
  onSeekEnd: (isPlaying) => {
    if (state.isPlaying) vid.play();
  },
  onProgress: progress, isSeeking => {
    if (!isSeeking) return;

    // set video time based on scrubber
    vid.currentTime = vid.duration * progress;
  }
});
```